version: "3"
services:
  app:
    image: best_insurance/api
    hostname: best_insurance_api
    container_name: best_insurance_api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/best_insurance_api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - 8080:8080
      - 5005:5005
  db:
    image: 'postgres:13'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: best_insurance_api
    volumes:
      - data_postgres_best_insurance:/var/lib/postgresql
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  data_postgres_best_insurance: {}
   